'use client';

import React from 'react';
import RadialChart from '@/shared/components/common/RadialChart/RadialChart';
import BarChart from '@/shared/components/common/BarChart/BarChart';
import DensityChart from '@/shared/components/common/DensityChart/DensityChart';

interface ChartData {
  name: string;
  value: number;
  color: string;
}

interface Chart {
  title: string;
  type: 'bar' | 'radial' | 'density';
  data: ChartData[];
}

export interface ChartVisualizationProps {
  address: string;
  charts: Record<string, Chart>;
  visualizationType: 'demographics' | 'safety' | 'health' | 'livability' | 'housing';
}

/**
 * Component for rendering data visualizations in chat messages
 * Displays charts generated by AI visualization tools
 */
export function ChartVisualization({ address, charts, visualizationType }: ChartVisualizationProps) {
  const chartEntries = Object.entries(charts);

  const typeLabels: Record<string, string> = {
    demographics: '📊 Demographics',
    safety: '🚨 Safety',
    health: '🏥 Health',
    livability: '🏡 Livability',
    housing: '🏘️ Housing Market',
  };

  return (
    <div className="my-4 p-4 bg-white border border-gray-200 rounded-lg shadow-sm">
      {/* Header */}
      <div className="mb-4 pb-3 border-b border-gray-200">
        <div className="flex items-center gap-2 mb-1">
          <h3 className="text-lg font-semibold text-gray-900">
            {typeLabels[visualizationType]}
          </h3>
        </div>
        <p className="text-sm text-gray-600">{address}</p>
      </div>

      {/* Charts */}
      <div className="space-y-6">
        {chartEntries.map(([key, chart]) => (
          <div key={key} className="bg-gray-50 rounded-lg p-4">
            <h4 className="text-base font-medium text-gray-800 mb-3">
              {chart.title}
            </h4>
            <div className="flex justify-center">
              {chart.type === 'bar' && (
                <BarChart
                  data={chart.data}
                  width={500}
                  height={300}
                  showLabels={true}
                />
              )}
              {chart.type === 'radial' && (
                <RadialChart
                  data={chart.data}
                  width={400}
                  height={350}
                  showLabels={true}
                  isSimple={false}
                />
              )}
              {chart.type === 'density' && (
                <DensityChart
                  data={chart.data.map((item, index) => ({ x: index, y: item.value }))}
                  width={500}
                  height={300}
                  mode="area"
                  tooltipLabels={chart.data.map(item => item.name)}
                />
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

ChartVisualization.displayName = 'ChartVisualization';

export default ChartVisualization;
